{
 "title": "Plant monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Tempreature",
   "type": "stat",
   "description": "Температура в комнате",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensor_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "description": "Влfжность в комнате",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensor_humidity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lux",
   "type": "gauge",
   "description": "Освещенность растения",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensor_lux", "legendFormat": "lux" }
   ]
  },
  {
   "title": "Height",
   "type": "stat",
   "description": "Высота растения",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensor_distance", "legendFormat": "Height" }
   ]
  },
  {
   "title": "All metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sensor_humidity ", "legendFormat": "humidity" },
    { "expr": "sensor_temperature", "legendFormat": "temreture" },
    { "expr": "sensor_distance", "legendFormat": "height" },
    { "expr": "sensor_lux", "legendFormat": "lux" }
   ]
  }
 ]
}