route:
  group_by: ['alertname']
  group_wait: 10m
  group_interval: 10m
  repeat_interval: 20m
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
    - chat_id: "your_chat_id"
      bot_token: "your_bot_token"
      send_resolved: true
      parse_mode: 'HTML'
      message: '{{ template "telegram.message". }}'

templates:
  - './message_templates/telegram.tmpl' # path to our telegram.tmpl